wandb_version: 1

architecture:
  desc: null
  value: ResNet50
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 1
num_samples_train:
  desc: null
  value: 0.8
num_samples_val:
  desc: null
  value: 0.1
num_samples_test:
  desc: null
  value: 0.1
species:
  desc: null
  value:
  - Fin
  - Blue
random_crop_secs:
  desc: null
  value: 5
df_dir:
  desc: null
  value: /home/usuaris/veussd/DATABASES/Ocean/dataframes
df_path:
  desc: null
  value: /home/usuaris/veussd/DATABASES/Ocean/dataframes/df_23_06_02_09_07_26_aty1jmit_wise-meadow-57.pkl
img_dir:
  desc: null
  value: /home/usuaris/veussd/DATABASES/Ocean/Spectrograms_AcousticTrends/23_06_02_09_07_26_aty1jmit_wise-meadow-57
save_dir:
  desc: null
  value: /home/usuaris/veussd/DATABASES/Ocean/checkpoints/
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686248369.823419
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.16
      5: 0.15.4
      8:
      - 5
      10:
      - 3
